---
title: "ce_read_hhi_data"
output: html_document
date: 1/7/21
---

## Read in household income data by Census tract from ACS5 2019

```{r}
library(tidycensus)
library(tidyverse)
library(dplyr)
library(plotly)
library(ggplot2)
library(readxl)
library(sf)
library(leaflet)
```

```{r}
# Check your API key
Sys.getenv("CENSUS_API_KEY")
```
Pull in ACS5 2019 Subject Table variables
```{r}
var_19_acs5_sub <- load_variables(year=2019, dataset="acs5/subject",cache=TRUE)
View(var_19_acs5_sub)

```

Tidycensus has a built in table of counties/states and FIPS codes.
```{r}

tidycensus::fips_codes

view(fips_codes%>%
    select(state, state_code) %>%
    distinct(.keep_all = False))

state_code_list <- pull(fips_codes %>%
                          select(state_code)%>%
                          distinct(.keep_all = FALSE), #dedupe state_code column
                        state_code
                        )[1:51] #exclude US territories

```

Read in selected variables ACS5 2019 Subject Table S1901 for TN, with polygon boundaries
```{r}
tn_hhi_g <-get_acs(survey = "acs5",
                        year=2019, 
                        #table="S1901",
                        variables=c(total_households="S1901_C01_001",
                                     median_hhi = "S1901_C01_012",
                                     mean_hhi="S1901_C01_013"),
                        geography="tract", 
                        state="TN",
                        cache=TRUE,
                        geometry = TRUE) %>%
            colname_cleanup()

head(tn_hhi_g)
glimpse(tn_hhi_g)
class(tn_hhi_g)
#view(tn_hhi_g)
```
Test plotting Davidson County Census data : Plotly
```{r}
p<-tn_hhi_g %>%
  filter(variable=="median_hhi") %>%
  filter(str_detect(name,"Davidson County")) %>%
  ggplot(aes(fill=estimate)) +
  geom_sf(color=NA) + #set 
  #coord_sf(crs=)
  scale_fill_viridis_c(option="plasma",
                       labels=scales::dollar)+
  theme_minimal() +
  labs(title="Tract-Level Median HHI",
       fill= "Median HHI")

fig <- ggplotly(p) 
fig

#Publish to plotly

Sys.setenv("plotly_username"="ceverest")
Sys.setenv("plotly_api_key"="V6TM2axFVMohJrseeMna")

#api_create(fig, filename = "median_hhi_davidson_co_tract")
```
Test plotting TN Census data - Leaflet

```{r}

tn_map_df <- tn_hhi_g%>%
  filter(variable == "mean_hhi")

glimpse(tn_map_df)
class(tn_map_df)

tn_pal <- colorNumeric(palette = "viridis",
                       domain=tn_map_df$estimate)

tn_map_df%>%
  leaflet()%>%
  addProviderTiles(providers$CartoDB.Positron)%>%
  #addTiles()%>%
  addPolygons(stroke=FALSE,
              fillOpacity=0.5,
              smoothFactor = 0.5,
              color= ~tn_pal(estimate),
              label = ~paste0(name,"<br/>",
                              "Estimate: $", estimate, "<br/>",
                              "Margin of Error: $", moe)%>%lapply(HTML),
              highlight = highlightOptions(weight=3,
                                           color="red",
                                           bringToFront = TRUE))%>%
  setView(lng= -86.7833322,
          lat=36.1500571,
          zoom=7)


```
